---
- hosts: all
  remote_user: root
  vars:
    - username1: student
  tasks:
    - name: check user info
      shell: id  {{ username1 }} || /bin/true
      register: result
    - debug:
        msg: "{{ result.stderr }} {{ result.stdout }}"
