---
- hosts: all
  remote_user: root
  vars:
    - username1: student
  tasks:
    - name: server name
      command: uname -n
      shell: cat /etc/passwd | grep {{ username1 }}
      user: name={{ username1 }}
