---
- hosts: all
  remote_user: root
  vars:
    - username1: student
  tasks:
    - name: server name
      command: hostname
    - name: get user id
      shell: cat /etc/passwd | grep {{ username1 }}
